# Generated by Django 3.2.7 on 2021-09-28 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orthoimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='panel_fault',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('px_x', models.IntegerField(default=0)),
                ('px_y', models.IntegerField(default=0)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ortho_viewer.orthoimage')),
            ],
        ),
    ]
