# Generated by Django 2.0.13 on 2021-11-11 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orthoimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='image/')),
                ('inspection_date', models.DateField(default='', null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='panel_fault',
            fields=[
                ('file', models.FileField(upload_to='')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('px_x', models.FloatField(default=1, null=True)),
                ('px_y', models.FloatField(default=1, null=True)),
                ('fault_image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ortho_viewer.Orthoimage')),
            ],
        ),
    ]
