# Generated by Django 3.2.7 on 2021-09-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ortho_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel_fault',
            name='px_x',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='panel_fault',
            name='px_y',
            field=models.IntegerField(default=1),
        ),
    ]
