# Generated by Django 2.0.13 on 2022-01-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ortho_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel_fault',
            name='fault_type',
            field=models.CharField(default='Bypass Fault', max_length=200),
        ),
    ]
