# Generated by Django 3.2.7 on 2021-11-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ortho_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orthoimage',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
