# Generated by Django 3.2.7 on 2021-09-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ortho_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orthoimage',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
