# Generated by Django 2.0.13 on 2022-01-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ortho_viewer', '0002_panel_fault_fault_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel_fault',
            name='fault_height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='panel_fault',
            name='fault_width',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='panel_fault',
            name='fault_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='panel_fault',
            name='fault_y',
            field=models.FloatField(default=0.0),
        ),
    ]
