# Generated by Django 2.0.13 on 2022-01-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ortho_viewer', '0003_auto_20220126_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel_fault',
            name='file',
        ),
    ]
