# Generated by Django 3.2.7 on 2021-09-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ortho_viewer', '0003_auto_20210929_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=40, null=True)),
                ('imgfile', models.ImageField(blank=True, null=True, upload_to='')),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='panel_fault',
            name='fault_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/fault'),
        ),
    ]
