# Generated by Django 3.2.7 on 2021-10-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ortho_viewer', '0005_auto_20210930_0349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterField(
            model_name='panel_fault',
            name='fault_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='panel_fault',
            name='px_x',
            field=models.FloatField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='panel_fault',
            name='px_y',
            field=models.FloatField(default=1, null=True),
        ),
    ]
